### ISSUE TITLE
Curses 2.2 does not have A_ITALIC

### ISSUE THREAD

**Issue by CobraCoral** [Jugran/lyrics-in-terminal#3]
I am using:

- Ubuntu 18.04.1
- Python 3.6.9
- Curses 2.2 (it is the version that gets installed with pip3 install curses)

and when I try to run lyrics, the following error happens:
$> lyrics
Traceback (most recent call last):
  File "/home/fcavalcanti/.local/bin/lyrics", line 8, in <module>
    sys.exit(start())
  File "/home/fcavalcanti/.local/lib/python3.6/site-packages/lyrics/lyrics_in_terminal.py", line 162, in start
    curses.wrapper(main, player_name, align=1)
  File "/usr/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/fcavalcanti/.local/lib/python3.6/site-packages/lyrics/lyrics_in_terminal.py", line 146, in main
    win = Window(stdscr, player, timeout=2000)
  File "/home/fcavalcanti/.local/lib/python3.6/site-packages/lyrics/lyrics_in_terminal.py", line 21, in __init__
    self.set_up()
  File "/home/fcavalcanti/.local/lib/python3.6/site-packages/lyrics/lyrics_in_terminal.py", line 30, in set_up
    self.set_titlebar()
  File "/home/fcavalcanti/.local/lib/python3.6/site-packages/lyrics/lyrics_in_terminal.py", line 43, in set_titlebar
    self.stdscr.addstr(2, 1, track_info[2], curses.A_REVERSE | curses.A_ITALIC)
AttributeError: module 'curses' has no attribute 'A_ITALIC'

**Comment by Jugran** [comment]
'A_ITALIC' support was added in Python 3.7.

I am removing italics font all together as it doesn't provide much visually.
PyPi will be updated later. 

Till then try to install script from source.
```sh
git clone https://github.com/Jugran/lyrics-in-terminal.git
cd lyrics-in-terminal
python setup.py install --user
```
